import time

mqttServoCMD = "SERVO/CMD"

def sequence(mqttPayload, client):
    client.publish(topic = mqttServoCMD, payload = mqttPayload, qos = 0, retain = False)
    time.sleep(1)
    client.publish(topic = mqttServoCMD, payload = "X", qos = 0, retain = False)

def sequenceTypeOne(client):
    sequence("RUN",client)
    sequence("RV50",client)
    time.sleep(1)
    sequence("STOP",client)
    sequence("START",client)
    sequence("LV100",client)
    time.sleep(3)
    sequence("LV300",client)
    time.sleep(3)
    sequence("RV50",client)
    time.sleep(2)
    sequence("STOP",client)
    sequence("OFF",client)

def sequenceTypeTwo(client):
    sequence("RUN",client)
    sequence("LV20",client)
    time.sleep(5)
    sequence("STOP",client)
    time.sleep(2)
    sequence("START",client)
    sequence("LV350",client)
    time.sleep(1)
    sequence("STOP",client)
    sequence("START",client)
    sequence("RV350",client)
    time.sleep(1)
    sequence("STOP",client)
    sequence("START",client)
    sequence("RV200",client)
    time.sleep(2)
    sequence("STOP",client)
    sequence("START",client)
    sequence("LV200",client)
    time.sleep(2)
    sequence("STOP",client)
    sequence("OFF",client)

def sequenceTypeThree(client):
    sequence("RUN",client)
    sequence("LV100",client)
    time.sleep(2)
    sequence("RV499",client)
    time.sleep(3)
    sequence("LV200",client)
    time.sleep(2)
    sequence("LV100",client)
    time.sleep(3)
    sequence("STOP",client)
    time.sleep(2)
    sequence("START",client)
    sequence("RV50",client)
    time.sleep(5)
    sequence("STOP",client)
    time.sleep(2)
    sequence("START",client)
    sequence("RV50",client)
    time.sleep(0.5)
    sequence("STOP",client)
    time.sleep(2)
    sequence("START",client)
    sequence("RV50",client)
    time.sleep(0.5)
    sequence("LV1",client)
    time.sleep(2)
    sequence("RV200",client)
    time.sleep(5)
    sequence("RV0.5",client)
    time.sleep(5)
    sequence("STOP",client)
    sequence("OFF",client)
